[package]
name = "sonic-pi-tool"
version = "0.1.0"
authors = ["Louis Pilfold <louis@lpil.uk>"]

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "sonic-pi-tool"
path = "src/main.rs"

[dependencies]
rosc = "~0.4"
clap = "~2.33"
nix = "~0.19"
ansi_term = "~0.12"
dirs = "~3.0"
